# Generated by Django 5.1.4 on 2024-12-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.URLField(max_length=2000),
        ),
    ]
