# Generated by Django 5.1.4 on 2024-12-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(upload_to='books/%y/%m/%d/'),
        ),
    ]
